kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: config-map-it-cluster-role
rules:
- apiGroups: [""]
  resources: ["secrets", "services", "pods", "namespaces"]
  verbs: ["get", "watch", "list"]