apiVersion: v1
kind: Service
metadata:
  name: config-map-it
  namespace: spring-k8s
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: config-map-it
    type: NodePort #ClusterIP